name: Update Wakatime Graph

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install --global wakatime-cli

      - name: Get Wakatime Stats
        run: wakatime --api-key ${{ secrets.WAKATIME_API_KEY }} --stats --write-stats /Users/hdeclerc/goinfre/stats.png

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git add /path/to/save/stats.png README.md
          git commit -m "Update Wakatime graph [skip ci]"
          git push
